name: pdf_env 
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.12
  - pip
  - chromadb==0.5.3
  - langchain==0.2.6
  - streamlit==1.36.0
  - transformers==4.41.2
  - pip:
    - langchain_huggingface==0.0.3
    - langchain_community==0.2.6 
    - torch==2.2.2









